UPSTREAM: x86emu: add console.h header to fix compilation
Commit 351e3e5 ("src: Use include <console/console.h> when appropriate")
has broken the build here, see below, so we include console.h here again.

In file included from src/device/oprom/x86emu/x86emui.h:65,
                  from src/device/oprom/x86emu/debug.c:40:
src/device/oprom/x86emu/debug.c: In function 'x86emu_dump_regs':
src/device/oprom/x86emu/debug.h:46:22: error: implicit declaration of function 'printk'; did you mean 'printf'?
[-Werror=implicit-function-declaration]
  #define printf(x...) printk(BIOS_DEBUG, x)
                       ^~~~~~
src/device/oprom/x86emu/debug.c:366:5: note: in expansion of macro 'printf'
      printf("\tAX=%04x  ", M.x86.R_AX );
      ^~~~~~

BUG=none
BRANCH=none
TEST=none

Change-Id: I710f7660e650f37d936891879af44619f3e0c87b
Signed-off-by: Martin Roth <martinroth@chromium.org>
Original-Commit-Id: d32a4930910dbe5dea47777902fcb966a4854114
Original-Fixes: 351e3e5 ("src: Use include <console/console.h> when appropriate")
Original-Change-Id: I75d0b7c08bfa6dcb07778bbb762223b62cfc3da7
Original-Signed-off-by: Martin Kepplinger <martink@posteo.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/32499
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: HAOUAS Elyes <ehaouas@noos.fr>
Original-Reviewed-by: Werner Zeh <werner.zeh@siemens.com>
Reviewed-on: https://chromium-review.googlesource.com/1593443