UPSTREAM: mb/emulation/qemu: Move packed attribute
The jenkins build complains about this now that clang has been added.

src/mainboard/emulation/qemu-q35/cpu.c:37:1: error:
attribute '__packed__' is ignored, place it after "union" to apply
attribute to type declaration [-Werror,-Wignored-attributes]
__packed union save_state {

(cherry picked from commit e13b263ef33664ff0029909479dedcfb832075ed)

Original-Signed-off-by: Martin Roth <gaumless@gmail.com>
Original-Change-Id: Id8faa24239505d808d09c00d825344edc7c4b7d9
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/69494
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Arthur Heymans <arthur@aheymans.xyz>
GitOrigin-RevId: e13b263ef33664ff0029909479dedcfb832075ed
Change-Id: Idec5d6e46e65e4d320f71ef63b6d551df73cb89e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4023033
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Paul Fagerburg <pfagerburg@chromium.org>
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>