UPSTREAM: soc/intel/common/block: Add missing include
Include types.h in src/soc/intel/common/block/include/intelblocks/cse.h
to use type bool.

Without this, there can be a build error like below,

src/soc/intel/common/block/include/intelblocks/cse.h:208:1:
 error: unknown type name 'bool'; did you mean '_Bool'?
 bool cse_is_hfs1_com_soft_temp_disable(void);
 ^~~~
 _Bool
src/soc/intel/common/block/include/intelblocks/cse.h:214:1:
 error: unknown type name 'bool'; did you mean '_Bool'?
 bool cse_is_hfs3_fw_sku_custom(void);

BUG=none
BRANCH=none
TEST=none

Change-Id: Ifad47258b7591993d3838e1654ade273cbdce3d7
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: b8b8ec832360ada5a313f10938bb6cfc310a11eb
Original-Signed-off-by: Rizwan Qureshi <rizwan.qureshi@intel.com>
Original-Change-Id: I92ee533bca7dc255f7a341b2a68bbc09900996a1
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/39922
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Paul Menzel <paulepanter@users.sourceforge.net>
Original-Reviewed-by: Patrick Georgi <pgeorgi@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2129694
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>