UPSTREAM: util/bucts: Fix compiler complaints shown with -Wextra
This fixes the following 2 complaints:

bucts.c: In function ‘main’:
error: unused parameter ‘envp’
error: ‘bucts_state’ may be used uninitialized in this function.

The bucts_state wasn't real, but the compiler couldn't tell, so use
one variable to check for modifications instead of two.

BUG=none
BRANCH=none
TEST=none

Change-Id: Iac5d3add64a0cfa7e0b47eadc712b40aa5b758f2
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 90a43067dda7a0c330b8a29a08ab3de6d1eae695
Original-Signed-off-by: Martin Roth <martin@coreboot.org>
Original-Change-Id: Iff1aae3441ec366d272e88b6b6634980d61cb8ea
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/50846
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Patrick Georgi <pgeorgi@google.com>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2718873
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>