UPSTREAM: lib/Makefile.inc: Correct filename to master_header_pointer.c
Builds are failing sporadically with:

src/lib/master_header_pointer.c:5:10: fatal error: fmap_config.h: No such file or directory
    5 | #include <fmap_config.h>
      |          ^~~~~~~~~~~~~~~

Correct the filename in the Makefile from header_pointer.c to
master_header_pointer.c so that there's a dependency from
master_header_pointer.c to fmap_config.h.

(cherry picked from commit 46af7f7442f53939130ed2eda2c00bb72cfa7746)

Signed-off-by: Reka Norman <rekanorman@chromium.org>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/64431
Reviewed-by: Arthur Heymans <arthur@aheymans.xyz>
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Patrick Georgi <patrick@coreboot.org>
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Change-Id: I41bcb2a21fdbc48f09d5b6be3e211ca56607d849
GitOrigin-RevId: 46af7f7442f53939130ed2eda2c00bb72cfa7746
Change-Id: I2b5feb16312b3a991a8d07273906007bcfbca811
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/3652660
Reviewed-by: Jonathon Murphy <jpmurphy@google.com>