UPSTREAM: Revert "mb/google/poppy: Nami - invoke power cycle of FPMCU on startup"
This reverts commit 2e6fa8206e0a3bdd2e53542b6377fe2b37e3f26e.

Reason for revert: causing `redefinition` issue.

src/mainboard/google/poppy/variants/nami/gpio.c:527:26: error: redefinition of 'variant_romstage_gpio_table'
const struct pad_config *variant_romstage_gpio_table(size_t *num)
                         ^
src/mainboard/google/poppy/variants/nami/gpio.c:426:26: note: previous definition is here
const struct pad_config *variant_romstage_gpio_table(size_t *num)
                         ^
(cherry picked from commit 9ac47c871f75dd17e27892293c7b94e4691631d0)

Original-Change-Id: I107cce8bf3a5bf38edb39b9d46512ee0d467d354
Original-Signed-off-by: Subrata Banik <subratabanik@google.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/73210
Original-Reviewed-by: Kapil Porwal <kapilporwal@google.com>
Original-Reviewed-by: Lean Sheng Tan <sheng.tan@9elements.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Nico Huber <nico.h@gmx.de>
GitOrigin-RevId: 9ac47c871f75dd17e27892293c7b94e4691631d0
Change-Id: Ib8373250901c171d8226db00c39e34ed14634b20
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4280740
Reviewed-by: Kangheui Won <khwon@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Commit-Queue: Kangheui Won <khwon@chromium.org>