UPSTREAM: xcompile: Explicitly disable warning address-of-packed-member
With GCC 9.x has a new warning *address-of-packed-member*.

> -Waddress-of-packed-member
>
>     Warn when the address of packed member of struct or union is
>     taken, which usually results in an unaligned pointer value.
>     This is enabled by default.

This results in the build errors below, for example, with GCC 9.2 from
Debian Sid/unstable.

    src/southbridge/intel/common/spi.c: In function 'spi_init':
    src/southbridge/intel/common/spi.c:298:19: error: taking address of packed member of 'struct ich7_spi_regs' may result in an unaligned pointer value [-Werror=address-of-packed-member]
      298 |   cntlr->optype = &ich7_spi->optype;
          |                   ^~~~~~~~~~~~~~~~~

Therefore, explicitly disable the warning.

BUG=none
BRANCH=none
TEST=none

Change-Id: I956ed4cd5d57db5f149e2efdd4be1ed046d16354
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: ceb7e68c48eafbfa9b735842159e01e8d2123a93
Original-Change-Id: I01d0dcdd0f8252ab65b91f40bb5f5c5e8177a293
Original-Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
Original-Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/36940
Original-Reviewed-by: Patrick Georgi <pgeorgi@google.com>
Original-Reviewed-by: Jacob Garber <jgarber1@ualberta.ca>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/1933268
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>