UPSTREAM: soc/amd: smbus: Use correct type for uintptr_t
Fix the format warning below by using `PRIxPTR`, which is defined as
unsigned long.

    src/soc/amd/common/block/smbus/smbus.c:33:56: error: format specifies type 'size_t' (aka 'unsigned int') but the argument has type 'uintptr_t' (aka 'unsigned long') [-Werror,-Wformat]
                    printk(BIOS_ERR, "Invalid SMBus or ASF base %#zx\n", mmio);
                                                                ~~~~     ^~~~
                                                                %#lx
    src/include/console/console.h:60:61: note: expanded from macro 'printk'
    #define printk(LEVEL, fmt, args...) do_printk(LEVEL, fmt, ##args)
                                                         ~~~    ^~~~
    1 error generated.

BUG=none
BRANCH=none
TEST=none

Signed-off-by: Martin Roth <gaumless@gmail.com>
Original-Commit-Id: cbd675173c3739b483f863aef85e02d8da95acc0
Original-Change-Id: I727c490d3097dcf36cdbcd4db2852cd49d11785f
Original-Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/51843
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Felix Held <felix-coreboot@felixheld.de>
Change-Id: Id7667d310628cba84c1e8945a97ce2a79d044f3c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2795719
Reviewed-by: Martin Roth <martinroth@google.com>
Commit-Queue: Martin Roth <martinroth@google.com>
Tested-by: Martin Roth <martinroth@google.com>