UPSTREAM: util/docker: Update dockerfiles
- Remove deprecated "MAINTAINER" lines
- Add Sphinx tools to coreboot-jenkins-node to check documentation.
- Add mdl to check markdown
- Alphabetize packages in docs Dockerfile
- Add jinja2 version 3.0.3 to the docs Dockerfile - The latest version
breaks with the error:
"exception: cannot import name 'contextfunction' from 'jinja2'"

(cherry picked from commit b3f91b79414c8ad49db80ca6b1c7036a951edfbb)

Original-Signed-off-by: Martin Roth <gaumless@gmail.com>
Original-Change-Id: Ia1de62621a6aef4ecd055a1a3afbebad34448002
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/64655
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Felix Singer <felixsinger@posteo.net>
GitOrigin-RevId: b3f91b79414c8ad49db80ca6b1c7036a951edfbb
Change-Id: I1556c0c139c49f1023769600c7d001b36752aae0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/3683482
Commit-Queue: Paul Fagerburg <pfagerburg@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>