UPSTREAM: Makefile: Do not use GCC specific options with LLVM/clang
Building with LLVM/clang (`COMPILER_LLVM_CLANG=y`), Debian clang version
11.0.1-2 fails due to unknown warning options.

    error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Werror,-Wunknown-warning-option]
    error: unknown warning option '-Wduplicated-cond' [-Werror,-Wunknown-warning-option]

As these are GCC specific, only add them, when building with GCC (and
not scan-build).

BUG=none
BRANCH=none
TEST=none

Change-Id: I743182d2d5d8fe3fa25a348f1ecebad54227f7a3
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 54d500788cbb724f83478cc57ce538baad066955
Original-Fixes: 04e0712f46 ("Treewide: Add some gcc's warning options")
Original-Change-Id: I6190c1f3df97fb0be51f8dab7e1f5f2a033f5d86
Original-Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/50771
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2704334
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>