UPSTREAM: sb/intel/common/acpi_pirq_gen.h: Fix conflicting types for 'is_slot_pin_assigned'
Found using 'Wenum-int-mismatch' (GCC-13: default with -Wall):
src/southbridge/intel/common/acpi_pirq_gen.c:69:6: error: conflicting types for 'is_slot_pin_assigned' due to enum/integer mismatch; have 'bool(const struct slot_pin_irq_map *, unsigned int,  unsigned int,  enum pci_pin)' {aka '_Bool(const struct slot_pin_irq_map *, unsigned int,  unsigned int,  enum pci_pin)'} [-Werror=enum-int-mismatch]
   69 | bool is_slot_pin_assigned(const struct slot_pin_irq_map *pin_irq_map,
      |      ^~~~~~~~~~~~~~~~~~~~
In file included from src/southbridge/intel/common/acpi_pirq_gen.c:8:
src/southbridge/intel/common/acpi_pirq_gen.h:91:6: note: previous declaration of 'is_slot_pin_assigned' with type 'bool(const struct slot_pin_irq_map *, unsigned int,  unsigned int,  unsigned int)' {aka '_Bool(const struct slot_pin_irq_map *, unsigned int,  unsigned int,  unsigned int)'}
   91 | bool is_slot_pin_assigned(const struct slot_pin_irq_map *pin_irq_map,
      |      ^~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 8f53e20955c7245861d3ad1a5ab29bc2d62c358d)

Original-cc1: all warnings being treated as errors
Original-Change-Id: Ie91947d00feaae42314ec2d1291f39d667a85346
Original-Signed-off-by: Elyes Haouas <ehaouas@noos.fr>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/70387
Original-Reviewed-by: Eric Lai <eric_lai@quanta.corp-partner.google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Tim Wawrzynczak <inforichland@gmail.com>
GitOrigin-RevId: 8f53e20955c7245861d3ad1a5ab29bc2d62c358d
Change-Id: Ie7027a3d99659893d0d118eff00d18c8f44bd368
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4101175
Reviewed-by: Reka Norman <rekanorman@chromium.org>
Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>