UPSTREAM: drivers/elog: Use format string
clang shows the warning below:

src/drivers/elog/elog.c:171:13: error:
format string is not a string literal
(potentially insecure) [-Werror,-Wformat-security]
            elog_debug(msg);
                       ^~~

(cherry picked from commit 24b7307d9dd686cf12921cb342db8108aa1ce564)

Original-Found-by: clang (13.0.1)
Original-Change-Id: I3f8949f9ce0c4ef4823530c61c503b0883bb5efc
Original-Signed-off-by: Matei Dibu <matdibu@protonmail.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/66262
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Matt DeVillier <matt.devillier@gmail.com>
GitOrigin-RevId: 24b7307d9dd686cf12921cb342db8108aa1ce564
Change-Id: I0dd2964f757b844bbfd5fdcf4a27a0f3279b8ff4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/3802986
Commit-Queue: Nick Vaccaro <nvaccaro@google.com>
Tested-by: CopyBot Service Account <copybot.service@gmail.com>
Reviewed-by: Nick Vaccaro <nvaccaro@google.com>