UPSTREAM: Revert "soc/amd/common/espi: Don't set alert pin in espi_set_initial_config"
This reverts commit 6eced03b25954e370e20e62f2cbe41f9d5626eae.

This prevents zork from booting. We get the following error:
eSPI cmd0-cmd2: 00080009 00000000 00000000 data: 00000000.
Error: unexpected eSPI status register bits set (Status = 0x10000010)
Error: Slave GET_CONFIGURATION failed!

This isn't a pure revert. It is more of a fix that keeps the old
behavior.

BUG=b:187122344
TEST=Boot zork an no longer see eSPI error

Change-Id: Ie458096d2b61f50d4ca0930b795d0f1c6b30cd9b
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: dcec409e95703b7a99600187e4b56c0b458114eb
Original-Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Original-Change-Id: If75a35d3994b0fd23945a450032d3cc81abeb136
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/53932
Original-Reviewed-by: Felix Held <felix-coreboot@felixheld.de>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2883474
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>