UPSTREAM: Revert "soc/intel/xeon_sp: Improve performance efficiencies"
This reverts commit d51449d017410fedb55e93f71fb322749ba888b5.

Reason for revert: Causing compilation issue as below

BUG=none
BRANCH=none
TEST=none

Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: ac17fad84e921209ff064c9258e3ad08bfba771c
Original-src/soc/intel/xeon_sp/cpx/acpi.c: In function 'acpi_create_rhsa':
Original-src/soc/intel/xeon_sp/cpx/acpi.c:825:4: error: initialization
Original-discards 'const' qualifier from pointer target type
Original-[-Werror=discarded-qualifiers]
Original-    &hob->PlatformData.IIO_resource[socket];
Original-    ^
Original-Change-Id: I7050060f1db7b9a9b5a77b5a6245c8fda05623a4
Original-Signed-off-by: Subrata Banik <subrata.banik@intel.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/44998
Original-Reviewed-by: Maxim Polyakov <max.senia.poliak@gmail.com>
Original-Reviewed-by: Patrick Georgi <pgeorgi@google.com>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>

Change-Id: I594d5bb7dd72aa0b125620cc92415f3e7ffc2d10
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2436146
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>