UPSTREAM: vc/eltan/security/verified_boot/vboot_check.c: Increase wb_buffer size
Running commit aee0baf0690681fae85d24e6887d6cbb9209de83 on
Facebook fbg1701 results in an error:
VB2:vb2_rsa_verify_digest() ERROR - vboot2 work buffer too small!
ERROR: HASH table verification failed!

The actual vboot structures require more space.
Workbuffer size needs to be increased.

We didn't determine the commit causing the issue because this change
fixes the issue.

BUG=N/A
TEST=Build and boot Facebook fbg1701

Change-Id: I6ed896a17dbe5a091fb05cbedb785b9b64dda315
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 7023174b88a2eca3f4eb541a2dc9cb7239617282
Original-Change-Id: I5caebc643eb493f4285c2f2fc164ff3a5d35e24e
Original-Signed-off-by: Frans Hendriks <fhendriks@eltan.com>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/40526
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Wim Vervoorn <wvervoorn@eltan.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2175872
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>