UPSTREAM: treewide: Remove unused #includes of spi_winbond.h
We want to add some function declarations as static_testable to this
header but including it in a .c file outside of tests will yield a gcc
warning like:

    error: 'function' declared 'static' but never defined
      [-Werror=unused-function]

It seems these includes aren't necessary anyways so we just remove
them.

BUG=none
BRANCH=none
TEST=none

Change-Id: I9e045e383d22ca39b5a22a454a48abec31b17f59
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 8438927879a73194924d6e1c021004fc3028b3b9
Original-Change-Id: I17147136579140b94728ceb1c369b1348714bc53
Original-Signed-off-by: Daniel Gröber <dxld@darkboxed.org>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/44090
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Frans Hendriks <fhendriks@eltan.com>
Original-Reviewed-by: HAOUAS Elyes <ehaouas@noos.fr>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2657640
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>