UPSTREAM: Makefile.inc: Use no-packed-not-aligned only with GCC
Clang doesn't know the warning `packed-not-aligned`, so only add it
when GCC is used.

    error: unknown warning option '-Wno-packed-not-aligned'; did you \
    mean '-Wno-over-aligned'? [-Werror,-Wunknown-warning-option]

BUG=none
BRANCH=none
TEST=none

Change-Id: Ic09ff5ecfd1a4066fe595d1e7bf41161989c7679
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 1619a3847594ecf6a5125d1030c8d86089dc7fda
Original-Change-Id: I86ee12a12fc24a0b8b92c4a0e665103ee4c4003d
Original-Signed-off-by: Paul Menzel <paulepanter@users.sourceforge.net>
Original-Reviewed-on: https://review.coreboot.org/26879
Original-Reviewed-by: Patrick Georgi <pgeorgi@google.com>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-on: https://chromium-review.googlesource.com/1124335
Commit-Ready: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>