UPSTREAM: cpu/x86/smm: Fix size_t type mismatch in print statement
The 64-bit compiler x86_64-linux-gnu-gcc-10 aborts the build with the
format warning below:

        CC         ramstage/cpu/x86/smm/smm_module_loader.o
    src/cpu/x86/smm/smm_module_loader.c: In function 'smm_module_setup_stub':
    src/cpu/x86/smm/smm_module_loader.c:360:70: error: format '%lx' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Werror=format=]
      360 |   printk(BIOS_ERR, "%s: state save size: %zx : smm_entry_offset -> %lx\n",
          |                                                                    ~~^
          |                                                                      |
          |                                                                      long unsigned int
          |                                                                    %x

As `size_t` is defined as `long unsigned int` in i386-elf (32-bit), the
length modifier `l` matches there. With x86_64-elf/x86_64-linux-gnu
(64-bit) and `-m32` `size_t` is defined as `unsigned int` resulting in a
type mismatch. So, use the correct length modifier `z` for the type
`size_t`.

BUG=none
BRANCH=none
TEST=none

Change-Id: Ifc52d9b50d5a4bf73471ccf5af0a0e0bba2cf270
Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Commit-Id: 85ac0675ed71ab9c5376e549c19267094491e980
Original-Found-by: x86_64-linux-gnu-gcc-10 (Debian 10.2.1-6) 10.2.1 20210110
Original-Fixes: afb7a814 ("cpu/x86/smm: Introduce SMM module loader version 2")
Original-Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Original-Change-Id: I4172e0f4dc40437250da89b7720a5c1e5fbab709
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/54342
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Werner Zeh <werner.zeh@siemens.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/2927568
Reviewed-by: Patrick Georgi <pgeorgi@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>