UPSTREAM: soc/intel/common/acpi/pep: Use correct size_t length modifier
Building an image for the Purism Mini v2 with `x86_64-linux-gnu-gcc-11`
fails with the format warning below as the size of size_t differs
between 32-bit and 64-bit.

        CC         ramstage/soc/intel/common/block/acpi/pep.o
    src/soc/intel/common/block/acpi/pep.c: In function 'read_pmc_lpm_requirements':
    src/soc/intel/common/block/acpi/pep.c:57:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
       57 |                                 printk(BIOS_ERR, "Failed to retrieve LPM substate registers"
          |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       58 |                                        "from LPM, substate %lu, reg %lu\n", i, j);
          |                                                                             ~
          |                                                                             |
          |                                                                             size_t {aka unsigned int}
    src/soc/intel/common/block/acpi/pep.c:58:62: note: format string is defined here
       58 |                                        "from LPM, substate %lu, reg %lu\n", i, j);
          |                                                            ~~^
          |                                                              |
          |                                                              long unsigned int
          |                                                            %u
    src/soc/intel/common/block/acpi/pep.c:57:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
       57 |                                 printk(BIOS_ERR, "Failed to retrieve LPM substate registers"
          |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       58 |                                        "from LPM, substate %lu, reg %lu\n", i, j);
          |                                                                                ~
          |                                                                                |
          |                                                                                size_t {aka unsigned int}
    src/soc/intel/common/block/acpi/pep.c:58:71: note: format string is defined here
       58 |                                        "from LPM, substate %lu, reg %lu\n", i, j);
          |                                                                     ~~^
          |                                                                       |
          |                                                                       long unsigned int
          |                                                                     %u

The variables `i` and `j` are of type size_t, so use the corresponding
length modifier `z`.

BUG=none
BRANCH=none
TEST=none

Signed-off-by: Patrick Georgi <pgeorgi@google.com>
GitOrigin-RevId: 5ca0015dc56db52062f5341f06c774abbb138f26
Original-Fixes: 2eb100dd ("soc/intel/common/block/acpi: Add LPM requirements support to PEPD _DSM")
Change-Id: I27bce0a6c62b1c1ebbca732761de2f59b042a5d4
Original-Signed-off-by: Paul Menzel <pmenzel@molgen.mpg.de>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/59057
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Tim Wawrzynczak <twawrzynczak@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/3378584
Tested-by: Paul Fagerburg <pfagerburg@chromium.org>
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>
Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Commit-Queue: Paul Fagerburg <pfagerburg@chromium.org>