UPSTREAM: util/cbfstool: Change %lu to %zu for size_t argument
With commit 34a7e66faa46 ("util/cbfstool: Add a new mechanism to
provide a memory map"), builds are failing on 32-bit platforms with:

../cbfstool/cbfstool.c:397:30: error: format specifies type 'unsigned long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                printf("Image SIZE %lu\n", image_size);
                                   ~~~     ^~~~~~~~~~
                                   %zu

Change the format specifier from %lu to %zu.

TEST=`emerge-cherry coreboot-utils` now succeeds

Cq-Depend: chromium:4112721

Original-Change-Id: I3602f57cf91c330122019bfa921faef6deb2b4ce
Original-Signed-off-by: Reka Norman <rekanorman@chromium.org>
Original-Reviewed-on: https://review.coreboot.org/c/coreboot/+/70848
Original-Reviewed-by: Elyes Haouas <ehaouas@noos.fr>
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Angel Pons <th3fanbus@gmail.com>
Original-Reviewed-by: Paul Menzel <paulepanter@mailbox.org>
Change-Id: I642367093285032c18ed8540f20e5799839a6f02
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/coreboot/+/4121755
Commit-Queue: Kangheui Won <khwon@chromium.org>
Tested-by: Kangheui Won <khwon@chromium.org>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>